# Generated by Django 6.0 on 2026-01-01 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseentry',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='financialgoal',
            name='target_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='incomeentry',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
