# Generated by Django 6.0 on 2026-01-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_expenseentry_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseentry',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='financialgoal',
            name='target_amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='incomeentry',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
