export type FinanceType = {
  id: string
  name: string
  icon?: string
}

export type CreateTypePayload = {
  name: string
}

export type CreateEntryPayload = {
  type: string
  amount: number
  date?: string
}

export type UpdateEntryPayload = {
  type?: string
  amount?: number
  date?: string
  note?: string
}

export type MonthlyReport = {
  month: string 
  totalIncome: number
  totalExpense: number
  balance: number
  incomeByType: Record<string, number>
  expenseByType: Record<string, number>
  goals?: GoalProgress[]
}

export type AutoGeneratedReport = {
  month: string
  generatedAt: string
  report: MonthlyReport
  summary: string
}

export type GoalProgress = {
  name: string
  type: PurposeType
  target: number
  progress: number
  percentage: number
}

export type LedgerKind = 'expense' | 'income' | 'all'

export type LedgerEntry = {
  id: number
  kind: Exclude<LedgerKind, 'all'>
  type: string
  amount: number
  date: string
  note?: string
}

export type LedgerResponse = {
  items: LedgerEntry[]
  page: number
  page_size: number
  total: number
}

export type PurposeType = 'expense' | 'income'

export type Purpose = {
  name: string
  type: PurposeType
  targetAmount: number
  currentAmount?: number
}

export type CreatePurposePayload = {
  name: string
  type: PurposeType
  target_amount: number
}

// Currently, UI only uses month; align with backend overview usage
export type ReportGenerateResponse = MonthlyReport
