export type FinanceType = {
  id: string
  name: string
  icon?: string
}

export type CreateTypePayload = {
  name: string
}

export type CreateEntryPayload = {
  type: string
  amount: number
  date?: string
}

export type MonthlyReport = {
  month: string 
  totalIncome: number
  totalExpense: number
  balance: number
  incomeByType: Record<string, number>
  expenseByType: Record<string, number>
}

export type AutoGeneratedReport = {
  month: string
  generatedAt: string
  report: MonthlyReport
  summary: string
}

export type PurposeType = 'expense' | 'income'

export type Purpose = {
  name: string
  type: PurposeType
  targetAmount: number
  currentAmount?: number
}

export type CreatePurposePayload = {
  name: string
  type: PurposeType
  target_amount: number
}

export type ReportGenerateResponse = {
  status: string
  file: string
  month: string
}
