<template>
  <div class="finance-view page-wrap">
    <!-- Header -->
    <header class="page-header">
      <div class="header-left">
        <h1>個人財務系統</h1>
      </div>
      <div class="header-right">
        <div class="user-info">
          <span class="user-icon">🙂</span>
          <span class="user-name">{{ user?.username || 'User' }}</span>
        </div>
        <button 
          class="ghost" 
          type="button" 
          @click="handleRefreshAll" 
          :disabled="loadingExpense || loadingIncome" 
          title="重新整理"
        >
          ↻
        </button>
        <button class="logout-btn" type="button" @click="handleLogout" title="登出">
          登出
        </button>
      </div>
    </header>

    <!-- Top Info Cards -->
    <div class="info-row">
      <div class="info-card">
        <p class="info-label">收入</p>
        <p class="info-value">NT$ {{ incomeTotal?.toLocaleString() || '0' }}</p>
      </div>
      <div class="info-card">
        <p class="info-label">支出</p>
        <p class="info-value">NT$ {{ expenseTotal?.toLocaleString() || '0' }}</p>
      </div>
      <div class="info-card">
        <p class="info-label">餘額</p>
        <p class="info-value" :class="{ negative: balance < 0 }">NT$ {{ balance?.toLocaleString() || '0' }}</p>
      </div>
    </div>

    <!-- Quick Add Form -->
    <QuickAddForm
      ref="quickAddFormRef"
      :expense-types="expenseTypes || []"
      :income-types="incomeTypes || []"
      :loading="entryLoading"
      :error="entryError || ''"
      :success="entrySuccess || ''"
      @submit="handleSubmitEntry"
    />

    <!-- Goals Section -->
    <GoalsSection
      :goals="goals || []"
      :loading="loadingGoals"
      :creating="creatingGoal"
      :error="errorGoals || ''"
      :insights="insights"
      :loading-insights="loadingInsights"
      :error-insights="errorInsights || ''"
      @submit-goal="handleSubmitGoal"
      @refresh-insights="loadInsights"
    />

    <!-- Analysis Grid -->
    <div class="analysis-grid">
      <StatsChart
        :active-tab="activeTab"
        :show-more="showMore"
        :has-more="hasMore"
        :loading="loadingExpense || loadingIncome"
        :has-data="hasData"
        :chart-option="chartOption"
        @update:active-tab="activeTab = $event"
        @toggle-show-more="showMore = !showMore"
      />

      <LedgerTable
        :items="ledgerItems"
        :kind="ledgerKind"
        :page="ledgerPage"
        :total="ledgerTotal"
        :page-size="ledgerPageSize"
        :loading="loadingLedger"
        :error="ledgerError || ''"
        @update:kind="handleSetKind"
        @prev-page="handlePrevPage"
        @next-page="handleNextPage"
        @edit-item="handleEditItem"
        @delete-item="handleDeleteItem"
      />
    </div>

    <!-- Monthly Report -->
    <MonthlyReport
      :report="monthlyReport"
      :loading="loadingReport"
      :error="reportError || ''"
      :selected-month="selectedMonth"
      @fetch-report="fetchReport"
      @update:selected-month="selectedMonth = $event"
    />

    <!-- Auto Report -->
    <AutoReport
      :report="autoReport"
      :loading-status="loadingReportStatus"
      @refresh="refreshAutoReport"
      @download-pdf="downloadPDF"
    />
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, onUnmounted, reactive, ref } from 'vue'
import { useRouter } from 'vue-router'
import { use } from 'echarts/core'
import { PieChart } from 'echarts/charts'
import { GridComponent, TooltipComponent, LegendComponent } from 'echarts/components'
import { CanvasRenderer } from 'echarts/renderers'

import SummaryBar from '@/components/SummaryBar.vue'
import QuickAddForm from '@/components/QuickAddForm.vue'
import GoalsSection from '@/components/GoalsSection.vue'
import StatsChart from '@/components/StatsChart.vue'
import LedgerTable from '@/components/LedgerTable.vue'
import MonthlyReport from '@/components/MonthlyReport.vue'
import AutoReport from '@/components/AutoReport.vue'

import { useFinanceData } from '@/composables/useFinanceData'
import { useAuth } from '@/composables/useAuth'
import { 
  generateMonthlyReport, 
  getLedger, 
  deleteExpenseEntry, 
  deleteIncomeEntry, 
  updateExpenseEntry, 
  updateIncomeEntry, 
  getInsights, 
  getReportStatus, 
  createExpenseEntry,
  createIncomeEntry
} from '@/api/finance'
import type { 
  MonthlyReport as MonthlyReportType, 
  AutoGeneratedReport, 
  ReportGenerateResponse, 
  LedgerEntry, 
  LedgerKind 
} from '@/types/finance'

use([CanvasRenderer, PieChart, GridComponent, TooltipComponent, LegendComponent])

const router = useRouter()
const { user, logout } = useAuth()
const quickAddFormRef = ref<InstanceType<typeof QuickAddForm> | null>(null)

// Finance Data Composable
const {
  expenseTypes,
  incomeTypes,
  expenseAmounts,
  incomeAmounts,
  expenseTotal,
  incomeTotal,
  goals,
  loadingExpense,
  loadingIncome,
  loadingGoals,
  loadingExpenseTotal,
  loadingIncomeTotal,
  errorGoals,
  balance,
  refreshAll,
  addGoal
} = useFinanceData()

// Insights
const insights = ref<string[]>([])
const loadingInsights = ref(false)
const errorInsights = ref<string | null>(null)

async function loadInsights() {
  loadingInsights.value = true
  errorInsights.value = null
  try {
    const res = await getInsights()
    insights.value = res.insights ?? []
  } catch (err) {
    errorInsights.value = err instanceof Error ? err.message : '無法取得建議'
  } finally {
    loadingInsights.value = false
  }
}

// Goals
const creatingGoal = ref(false)

async function handleSubmitGoal(form: { name: string; type: string; target_amount: number; target_month: string }) {
  creatingGoal.value = true
  try {
    await addGoal({
      name: form.name,
      type: form.type as 'income' | 'expense',
      target_amount: form.target_amount,
      target_month: form.target_month ? `${form.target_month}-01` : undefined
    })
    await loadInsights()
  } catch (err) {
    console.error('Failed to create goal', err)
  } finally {
    creatingGoal.value = false
  }
}

// Charts
const activeTab = ref<'expense' | 'income'>('expense')
const showMore = ref(false)

const expenseRank = computed(() => 
  (expenseTypes?.value ?? []).map(t => ({ 
    category: t.name, 
    total: expenseAmounts.value?.[t.name] ?? 0 
  }))
)

const incomeRank = computed(() => 
  (incomeTypes?.value ?? []).map(t => ({ 
    category: t.name, 
    total: incomeAmounts.value?.[t.name] ?? 0 
  }))
)

const activeRank = computed(() => 
  activeTab.value === 'expense' ? expenseRank.value : incomeRank.value
)

const filteredRank = computed(() => activeRank.value.filter(r => r.total > 0))
const sortedRank = computed(() => [...filteredRank.value].sort((a, b) => b.total - a.total))
const limit = computed(() => (showMore.value ? 10 : 5))
const slicedRank = computed(() => sortedRank.value.slice(0, limit.value))
const hasData = computed(() => filteredRank.value.length > 0)
const hasMore = computed(() => filteredRank.value.length > 5)

const chartOption = computed(() => ({
  tooltip: {
    trigger: 'item',
    formatter: (p: any) => `${p.name}: NT$ ${Number(p.value ?? 0).toLocaleString()} (${p.percent}%)`
  },
  legend: {
    type: 'scroll',
    orient: 'horizontal',
    bottom: 0,
    left: 'center',
    icon: 'circle',
    itemWidth: 10,
    itemHeight: 10,
    textStyle: { color: '#374151', fontSize: 12 }
  },
  color: activeTab.value === 'expense'
    ? ['#f97316', '#fb923c', '#fdba74', '#fed7aa', '#ffedd5']
    : ['#22c55e', '#34d399', '#6ee7b7', '#a7f3d0', '#d1fae5'],
  series: [{
    name: activeTab.value === 'expense' ? '支出' : '收入',
    type: 'pie',
    radius: ['32%', '60%'],
    center: ['50%', '42%'],
    label: {
      show: slicedRank.value.length <= 5,
      formatter: (p: any) => `${p.name}\n${p.percent}%`,
      fontSize: 13
    },
    data: slicedRank.value.map(x => ({ name: x.category, value: x.total }))
  }]
}))

// Entry Form
const entryLoading = ref(false)
const entryError = ref<string | null>(null)
const entrySuccess = ref<string | null>(null)
let successTimer: number | undefined

async function handleSubmitEntry(form: { type: string; amount: number; date: string }) {
  entryError.value = null
  entrySuccess.value = null
  if (successTimer) {
    clearTimeout(successTimer)
    successTimer = undefined
  }
  entryLoading.value = true
  
  try {
    const kind = quickAddFormRef.value?.getKind() || 'expense'
    
    if (kind === 'expense') {
      const res = await createExpenseEntry({ 
        type: form.type, 
        amount: form.amount, 
        date: form.date 
      })
      entrySuccess.value = res?.warning ? `新增成功（提醒：${res.warning}）` : '新增成功'
    } else {
      await createIncomeEntry({ 
        type: form.type, 
        amount: form.amount, 
        date: form.date 
      })
      entrySuccess.value = '新增成功'
    }
    
    quickAddFormRef.value?.reset()
    await Promise.all([refreshAll(), fetchLedger()])
    await loadInsights()
    successTimer = window.setTimeout(() => {
      entrySuccess.value = null
      successTimer = undefined
    }, 3000)
  } catch (err) {
    entryError.value = err instanceof Error ? err.message : '新增失敗'
  } finally {
    entryLoading.value = false
  }
}

// Ledger
const ledgerKind = ref<LedgerKind>('all')
const ledgerPage = ref(1)
const ledgerPageSize = ref(10)
const ledgerTotal = ref(0)
const ledgerItems = ref<LedgerEntry[]>([])
const loadingLedger = ref(false)
const ledgerError = ref<string | null>(null)

async function fetchLedger() {
  loadingLedger.value = true
  ledgerError.value = null
  try {
    const res = await getLedger({ kind: ledgerKind.value, page: ledgerPage.value, pageSize: ledgerPageSize.value })
    ledgerItems.value = res.items
    ledgerTotal.value = res.total
  } catch (err) {
    ledgerError.value = err instanceof Error ? err.message : '取得紀錄失敗'
  } finally {
    loadingLedger.value = false
  }
}

function handleSetKind(kind: LedgerKind) {
  ledgerKind.value = kind
  ledgerPage.value = 1
  fetchLedger()
}

function handlePrevPage() {
  if (ledgerPage.value > 1) {
    ledgerPage.value--
    fetchLedger()
  }
}

function handleNextPage() {
  const maxPage = Math.max(1, Math.ceil(ledgerTotal.value / ledgerPageSize.value))
  if (ledgerPage.value < maxPage) {
    ledgerPage.value++
    fetchLedger()
  }
}

async function handleEditItem(item: LedgerEntry, draft: { date: string; amount: number }) {
  try {
    if (item.kind === 'expense') {
      await updateExpenseEntry(item.id, { amount: draft.amount, date: draft.date })
    } else {
      await updateIncomeEntry(item.id, { amount: draft.amount, date: draft.date })
    }
    await Promise.all([refreshAll(), fetchLedger()])
  } catch (err) {
    ledgerError.value = err instanceof Error ? err.message : '更新失敗'
  }
}

async function handleDeleteItem(item: LedgerEntry) {
  try {
    if (item.kind === 'expense') {
      await deleteExpenseEntry(item.id)
    } else {
      await deleteIncomeEntry(item.id)
    }
    await Promise.all([refreshAll(), fetchLedger()])
  } catch (err) {
    ledgerError.value = err instanceof Error ? err.message : '刪除失敗'
  }
}

// Monthly Report
const selectedMonth = ref(new Date().toISOString().slice(0, 7))
const monthlyReport = ref<MonthlyReportType | null>(null)
const loadingReport = ref(false)
const reportError = ref<string | null>(null)

async function fetchReport() {
  if (!selectedMonth.value) return
  loadingReport.value = true
  reportError.value = null
  monthlyReport.value = null
  
  try {
    const response: ReportGenerateResponse = await generateMonthlyReport(selectedMonth.value)
    monthlyReport.value = {
      month: response.month,
      totalIncome: response.totalIncome,
      totalExpense: response.totalExpense,
      balance: response.balance,
      incomeByType: response.incomeByType,
      expenseByType: response.expenseByType,
      goals: response.goals
    }
  } catch (err) {
    reportError.value = err instanceof Error ? err.message : '取得報表失敗'
  } finally {
    loadingReport.value = false
  }
}

// Auto Report
const autoReport = ref<AutoGeneratedReport | null>(null)
const loadingReportStatus = ref(false)

async function refreshAutoReport() {
  const prevMonth = new Date()
  prevMonth.setMonth(prevMonth.getMonth() - 1)
  const month = prevMonth.toISOString().slice(0, 7)
  await loadAutoReport(month)
}

async function loadAutoReport(month: string) {
  try {
    const response: ReportGenerateResponse = await generateMonthlyReport(month)
    const summary = generateSummary(response)

    autoReport.value = {
      month: response.month,
      generatedAt: new Date().toISOString(),
      report: response,
      summary
    }
  } catch (err) {
    console.error('Failed to load auto report', err)
  }
}

function generateSummary(report: MonthlyReportType): string {
  const { totalIncome, totalExpense, balance } = report
  
  let summary = `本月總收入為 NT$ ${totalIncome.toLocaleString()}，總支出為 NT$ ${totalExpense.toLocaleString()}，`

  if (balance > 0) {
    summary += `結餘 NT$ ${balance.toLocaleString()}，財務狀況良好。`
  } else if (balance < 0) {
    summary += `赤字 NT$ ${Math.abs(balance).toLocaleString()}，建議控制支出。`
  } else {
    summary += `收支平衡。`
  }
  
  return summary
}

async function downloadPDF() {
  try {
    // @ts-ignore
    const html2pdf = (await import('html2pdf.js')).default as any
    const element = document.getElementById('auto-report-content')
    
    if (!element) throw new Error('Report element not found')
    
    const opt = {
      margin: 10,
      filename: `財務報表_${autoReport.value?.month}.pdf`,
      image: { type: 'jpeg', quality: 0.98 },
      html2canvas: { scale: 2 },
      jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' }
    }
    
    await html2pdf().set(opt).from(element).save()
  } catch (err) {
    console.error('PDF 下載失敗', err)
    alert('PDF 下載失敗，請稍後再試')
  }
}

// Lifecycle
async function handleLogout() {
  await logout()
  router.replace('/login')
}

async function handleRefreshAll() {
  await Promise.all([refreshAll(), fetchLedger()])
}

onMounted(() => {
  refreshAll()
  loadInsights()
  fetchLedger()
  refreshAutoReport()
})

onUnmounted(() => {
  if (successTimer) {
    clearTimeout(successTimer)
    successTimer = undefined
  }
})
</script>

<style scoped>
.page-wrap {
  max-width: 1200px;
  margin: 0 auto;
  padding: 2rem 1.25rem 3rem;
  min-height: 100vh;
  color: var(--text);
}

.page-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 1.5rem;
  padding: 1.1rem 1.25rem;
  background: var(--surface);
  border-radius: 14px;
  border: 1px solid #e5e7eb;
  box-shadow: 0 10px 26px rgba(15, 23, 42, 0.08);
  color: var(--text);
}

.page-header h1 {
  margin: 0;
  font-size: 1.7rem;
  letter-spacing: 0.01em;
  color: #0f172a;
}

.header-right {
  display: flex;
  gap: 1rem;
  align-items: center;
}

.user-info {
  display: flex;
  align-items: center;
  gap: 0.5rem;
}

.user-icon {
  font-size: 1.5rem;
}

.user-name {
  font-weight: 600;
  color: #0f172a;
}

button.ghost {
  background: #f8fafc;
  border: 1px solid #e5e7eb;
  padding: 0.55rem 0.95rem;
  border-radius: 10px;
  cursor: pointer;
  font-size: 1.05rem;
  color: #0f172a;
  transition: transform 0.12s ease, box-shadow 0.12s ease, background 0.12s ease;
}

button.ghost:hover:not(:disabled) {
  background: #eef2ff;
  transform: translateY(-1px);
  box-shadow: 0 10px 30px rgba(15, 23, 42, 0.12);
}

button.ghost:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

.logout-btn {
  background: linear-gradient(135deg, #ef4444, #dc2626);
  color: white;
  border: none;
  padding: 0.55rem 1rem;
  border-radius: 10px;
  cursor: pointer;
  font-weight: 600;
  box-shadow: 0 10px 24px rgba(220, 38, 38, 0.28);
  transition: transform 0.12s ease, box-shadow 0.12s ease;
}

.logout-btn:hover {
  transform: translateY(-1px);
  box-shadow: 0 12px 30px rgba(220, 38, 38, 0.36);
}

.analysis-grid {
  display: grid;
  grid-template-columns: 1fr 2fr;
  gap: 1.5rem;
  margin-bottom: 1.5rem;
}

.info-row {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
  gap: 1rem;
  margin: 0 0 1.5rem;
}

.info-card {
  background: #ffffff;
  border: 1px solid #e5e7eb;
  border-radius: 12px;
  padding: 1rem 1.1rem;
  box-shadow: 0 8px 22px rgba(15, 23, 42, 0.08);
}

.info-label {
  margin: 0 0 0.35rem;
  color: var(--text-muted);
  font-size: 0.95rem;
  letter-spacing: 0.01em;
}

.info-value {
  margin: 0;
  font-size: 1.4rem;
  font-weight: 700;
  color: #0f172a;
}

.info-value.negative {
  color: #dc2626;
}

@media (max-width: 1024px) {
  .analysis-grid {
    grid-template-columns: 1fr;
  }
}
</style>
